name: Main workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - release
      - master
    types: [opened, synchronize, closed]
jobs:
  tests:
    name: Test
    # if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Debug Info
        run: |
          whoami
          groups $USER
          env
      - name: Check Docker version
        run: docker --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set environment variables
        run: |
          if [[ $GITHUB_REF == refs/heads/develop ]]; then
            export MYSQL_USER="${{ secrets.DB_DEV_USER }}"
            export MYSQL_PWD="${{ secrets.DB_DEV_PASSWORD }}"
            export MYSQL_HOST="${{ secrets.DB_DEV_HOST }}"
            export MYSQL_PORT="${{ secrets.DB_DEV_PORT }}"
            export MYSQL_DB="${{ secrets.DB_DEV_DATABASE }}"
          elif [[ $GITHUB_REF == refs/heads/release ]]; then
            export MYSQL_USER="${{ secrets.DB_STAGING_USER }}"
            export MYSQL_PWD="${{ secrets.DB_STAGING_PASSWORD }}"
            export MYSQL_HOST="${{ secrets.DB_STAGING_HOST }}"
            export MYSQL_PORT="${{ secrets.DB_STAGING_PORT }}"
            export MYSQL_DB="${{ secrets.DB_STAGING_DATABASE }}"
          elif [[ $GITHUB_REF == refs/heads/master ]]; then
            export MYSQL_USER="${{ secrets.DB_PROD_USER }}"
            export MYSQL_PWD="${{ secrets.DB_PROD_PASSWORD }}"
            export MYSQL_HOST="${{ secrets.DB_PROD_HOST }}"
            export MYSQL_PORT="${{ secrets.DB_PROD_PORT }}"
            export MYSQL_DB="${{ secrets.DB_PROD_DATABASE }}"
          fi
      - name: Echo
        run: |
          echo $MYSQL_USER
          echo $MYSQL_PWD
          echo $MYSQL_HOST
          echo $MYSQL_PORT
          echo $MYSQL_DB
      - name: Install dependencies
        run: |
          pwd
          ls
          pip install -r pip-requirements.txt
      - name: Run
        run: |
          python model.py

